### PR TITLE
Creating a visual reference too recipe's origin

### PR DESCRIPTION
**Pull request by stephenpaulger**
screen shot 2016-05-18 at 00 07 39

I've not got the vertical alignment right yet, let me know if that's worth looking at or reject it now if you're not keen.

### CODE REVIEW

**Comment by user24** [comment]
Ha, nice. I like the idea of adding a visual reference, but I think it's a bit heavy like this.

**Comment by user24** [comment]
If we add pagination, it would be pretty cool to use the black-box-white-text style for the page numbers, similar to how goooooooogle do it.

**Comment by alexellis** [comment]
@stephenpaulger can you do a CSS style sheet please.. ? :)

**Comment by stephenpaulger** [comment]
Hi @alexellis I'm not sure if I'm misunderstanding what you're asking for. The style is [in the HTML file in the branch logoreference on my fork, the class is called logoletter](https://github.com/stephenpaulger/auntiesrecipes/blob/logoreference/index.html#L14).

**Comment by alexellis** [comment]
Style in a .css, less or sass file is what I meant. I.e. separate file
instead of inline. What do you think?

**Comment by user24** [comment]
Closing this as css/js extraction covered in https://github.com/user24/auntiesrecipes/pull/10

**Pull request closed without merging**
